module 11: Removed Heroku deployment and added azure deployment instead
jatin-28/DevOps-Course-Starter pull request #16
Opened 2021-05-31 10:36 UTC by jatin-28

2021-06-04 11:41 UTC, hugh-emerson requested changes
You are publicly sharing your app's deployment password. This needs to be secured as any other password (and you should treat this password as compromised - you can reset it through the portal)

2021-06-04 20:34 UTC, jatin-28 commented
> You are publicly sharing your app's deployment password. This needs to be secured as any other password (and you should treat this password as compromised - you can reset it through the portal)

Done!

2021-06-14 16:10 UTC, hugh-emerson requested changes
You are now leaking the new password.

Also, the last deployment failed because you wrapped your curl command in quotes.

2021-06-21 08:56 UTC, hugh-emerson approved these changes
Looks good! 👍 Merge when you're ready

But I suggest you delete commented out code (both Python and Dockerfile commands). They're safely stored in git if you do want to switch back to Firefox later.

Resubmit it in Aptem and we can approve it there.

2021-06-21 08:56 UTC, hugh-emerson commented on .travis.yml
> +    branch: module_11
Don't forget to update this.

2021-06-21 09:31 UTC, merged